require 'plugins.tokyonight'
require 'plugins.cyberdream'

-- load colorscheme
vim.cmd.colorscheme 'cyberdream'

require 'plugins.snacks'
require 'plugins.persistence'
require 'plugins.mini'
require 'plugins.blink-cmp'
require 'plugins.mason'
require 'plugins.mason-tool-installer'
require 'plugins.lsp'
require 'plugins.conform'
require 'plugins.treesitter'
require 'plugins.flash'
require 'plugins.yanky'
require 'plugins.dap'
require 'plugins.bufferline'
require 'plugins.lualine'
require 'plugins.starter'
